[build]
  publish = "_site"
  command = "npm run build"
[[redirects]]
from = "https://www.esculture.es/*"
  to = "https://www.mussaart.com/"
  status = 301
  force = true
[[redirects]]
from = "https://esculture.es/*"
  to = "https://www.mussaart.com/"
  status = 301
  force = true